apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
  - name: keycloak
    port: 8080
    protocol: TCP    
    nodePort: 31080
  type: NodePort