apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - yaml/secret-postgres.yaml
  - yaml/persistence-volume-claim.yaml
  - yaml/persistence-volume.yaml
  - yaml/deployment-postgres.yaml
  - yaml/service-postgres.yaml
  
namespace: foxcorp  

configMapGenerator:
- name: postgres-init-script-configmap
  files:
  - initdb.sh

commonLabels:
  author: lmoyano
  
